## https://github.com/sharadkhare/Complete-Python-NumPy-Tutorial-in-Hindi-With-Notes-

In [1]:
#installation of numpy
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
sharad = np.array([1,2,3,4,5])
print(sharad)

[1 2 3 4 5]


In [3]:
import numpy as np
print(np.__version__)

1.24.4


In [5]:
#create a numpy ndarray object - for creating ndarray we need to use array()

import numpy as np
a = np.array([1,2,3,4,5])
print(a)
print(type(a))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
#what ever object you will pass in it, it will automatically get converted in nd array
import numpy as np 
aj = np.array((1,2,3,4,5))
print(aj)
print(type(aj))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
#dimension of array - nested array 
# 0D - create
import numpy as np
aj1 = np.array(50)
print(aj1)

50


In [9]:
# create 1D
import numpy as np
aj1 = np.array([1,2,3,4,5])
print(aj1)

[1 2 3 4 5]


In [13]:
# create 2D
import numpy as np
aj1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(aj1)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [14]:
# create 3D
import numpy as np
aj1 = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(aj1)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [15]:
#checking the number of dimensions?
#ndim
import numpy as np
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3,],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
#higher dimension arrays - you can define the number of dimension by using ndmin argument
import numpy as np
b = np.array([1,2,3,4,5],ndmin=5)
print(b)
print("number of dimension are:",b.ndim)

[[[[[1 2 3 4 5]]]]]
number of dimension are: 5


In [19]:
# how to access the array elements
# indexes in numpy are also starts with 0
import numpy as np
aj = np.array([1,2,3,4,5])
print(aj[1])

2


In [20]:
aj = np.array([1,2,3,4,5])
print(aj[1]+aj[2]) # 1D

5


In [22]:
#access 2D
aj1 = np.array([[1,2,4,5,6],[5,6,7,8,9]])
print('2nd element on the first row is :',aj1[0,1])
print('3nd element on the second row is :',aj1[1,2])

2nd element on the first row is : 2
2nd element on the first row is : 7


In [23]:
# accessing 3D
aj2 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

# lets print 3rd element of 2nd array of the 1st array
print(aj2[0,1,2])

6


In [24]:
# how to access element from negative indexing
aj3 = np.array([[1,2,3,4,5],[5,6,7,8,9]])
print('last element from the 2nd dimension is: ',aj3[1,-1])

last element from the 2nd dimension is:  9


In [25]:
# numpy array slicing 
# [start:end] or [start:end:step]
#slice element from index 1 to index 5

import numpy as np
aj4 = np.array([1,2,3,4,5,6,7])
print(aj4[1:5])

[2 3 4 5]


In [26]:
#slice the element from index 4 to the end
aj4 = np.array([1,2,3,4,5,6,7])
print(aj4[4:])

[5 6 7]


In [27]:
# slice the elemnt from the neginning to index no 4
aj4 = np.array([1,2,3,4,5,6,7])
print(aj4[:4])

[1 2 3 4]


In [28]:
# negative indexing  - use minus operator to refer to an index from end 
# slice from the index 3 from the end

aj5 = np.array([1,2,3,4,5,6,7])
print(aj5[4:])

[5 6 7]


In [30]:
#step in slicing
#return every other element from index 1 to index 5
aj5 = np.array([1,2,3,4,5,6,7])
print(aj5[1:5:2])

[2 4]


In [31]:
#return every other element from whole array
aj5 = np.array([1,2,3,4,5,6,7])
print(aj5[::2])

[1 3 5 7]


In [32]:
#slicing the 2D array
# from the 2nd element, slice element from the index 1 to index 4 
aj6 = np.array([[1,2,3,4,5],[5,6,7,9,8]])
print(aj6[1,1:4])

[6 7 9]


In [33]:
# from both elements, return index 2
aj6 = np.array([[1,2,3,4,5],[5,6,7,9,8]])
print(aj6[0:2,2])

[3 7]


In [34]:
# from both element , we will slice index 1 to 4 index(not included ), this will return a 2 d array
aj6 = np.array([[1,2,3,4,5],[5,6,7,9,8]])
print(aj6[0:2,1:4])

[[2 3 4]
 [6 7 9]]


In [36]:
#numpy  data types
#like i for int, b for boolean , f for float
# the numpy array object has a property called dtype that return the data type of an array

aj7 = np.array([1,2,3,4])
print(aj7.dtype)

int64


In [38]:
aj7 = np.array(['ajay','amit','sumit'])
print(aj7.dtype)

<U5


In [40]:
# creating array with a defined data type
aj8 = np.array([1,2,3,4],dtype='S')
print(aj8)
print(aj8.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [41]:
# create an array with a data type 4 bytes integer
aj9 = np.array([1,2,3,4],dtype='i4')
print(aj9)
print(aj9.dtype)

[1 2 3 4]
int32


In [44]:
# value error 
aj9 = np.array(['a','2','3'],dtype='i')

print(aj9.dtype)

ValueError: invalid literal for int() with base 10: 'a'

In [47]:
#converting  data type on an existing arrays() - astype()
# example - change data type from float to integer by using 'i'

a10 = np.array([1.1,2.1,4.1])
a101 = a10.astype('i')
print(a101)
print(a101.dtype)

[1 2 4]
int32


In [49]:
# change data type from integer to boolean
b = np.array([1,2,3,4,0])
b1 = b.astype(bool)
print(b1)
print(b1.dtype)

[ True  True  True  True False]
bool


In [ ]:
# List of all data type in numpy
i - integer
b - boolean
c - insigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - Unicode string


In [50]:
# the difference between copy and view
# example of copy (dosent affect)

c = np.array([1,2,3,4,5])
x = c.copy()
c[0] = 45
print(c)
print(x)

[45  2  3  4  5]
[1 2 3 4 5]


In [51]:
# example of view (affect)

c = np.array([1,2,3,4,5])
x = c.view()
c[0] = 45
print(c)
print(x)

[45  2  3  4  5]
[45  2  3  4  5]


In [52]:
# check if array owns its data
# print the value of the base attribute to check if an array own its data or not

# example of copy (dosent affect)

c = np.array([1,2,3,4,5])
x = c.copy()
y = c.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


In [53]:
# numpy array shapes
# print the shape of 2 d array
d = np.array([[1,2,3,4],[5,6,7,8]])
print(d.shape)

(2, 4)


In [54]:
d = np.array([1,2,3,4,5],ndmin = 5)
print(d)
print('shape of array :',d.shape)

[[[[[1 2 3 4 5]]]]]
shape of array : (1, 1, 1, 1, 5)


In [ ]:
# what does the shape tuple reperesnts?

In [56]:
# numpy array reshaping
# reshape from 1d to 2d

e = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
e1 = e.reshape(4,3)
print(e1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [57]:
# reshape from 1d to 3d
e = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
e1 = e.reshape(2,3,2)
print(e1)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [58]:
# can we reshape into any shape
# try to convert 1d array with 8 element to 2d array with 3 element each dimension
e = np.array([1,2,3,4,5,6,7])
e1 = e.reshape(3,3)
print(e1)

ValueError: cannot reshape array of size 7 into shape (3,3)

In [59]:
# converting 1d array to 8 element to 3d (2*2)
e = np.array([1,2,3,4,5,6,7,8])
e1 = e.reshape(2,2,-1) # unknown dim
print(e1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [60]:
# flattening the array
#use reshape (-1)
d = np.array([[1,2,3],[4,5,6]])
d1 = d.reshape(-1)
print(d1)

[1 2 3 4 5 6]


In [61]:
# numpy array iterating
#iterating 1d example

g = np.array([1,2,3,4]) #1d
for x in g:
    print(x)

1
2
3
4


In [63]:
#iterating 2d example

g = np.array([[1,2,3],[4,5,6]]) #2d
for x in g:
    print(x)

[1 2 3]
[4 5 6]


In [64]:
#iterating on each scale element of 2d 
g = np.array([[1,2,3],[4,5,6]]) #2d
for x in g:
    for y in x:
        print(y)

1
2
3
4
5
6


In [68]:
g = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[6,7,8]]]) #3d
for x in g:
    print(x)

[[1 2 3]
 [4 5 6]]
[[4 5 6]
 [6 7 8]]


In [67]:
#iterating on each scale element of 3d 
g = np.array([[[1,2,3],[4,5,6]],[[4,5,6],[6,7,8]]]) #3d
for x in g:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
4
5
6
6
7
8


In [69]:
# you can use another way by using nditer()
# iterate through  3d by using nditer()
a = np.array([[[1,2],[3,4]],[[4,5],[6,7]]])
for x in np.nditer(a):
    print(x)

1
2
3
4
4
5
6
7


In [70]:
# joining the numpy arrays 
# join 2 array

a = np.array([1,2,3,4])
a1 = np.array([4,5,6,7])
a2 = np.concatenate((a,a1))
print(a2)

[1 2 3 4 4 5 6 7]


In [72]:
# join two 2d along with rows (axis = 1)
a = np.array([[1,2],[3,4]])
a1 = np.array([[11,21],[31,41]])
a2 = np.concatenate((a,a1),axis=1)
print(a2)

[[ 1  2 11 21]
 [ 3  4 31 41]]


In [73]:
# joining the array using stack func.
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.stack((a,b),axis=1)
print(c)

[[1 4]
 [2 5]
 [3 6]]


In [76]:
#different types of stack.(very important)
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.hstack((a,b))
d = np.vstack((a,b))
e = np.dstack((a,b))
print(c)
print(d)
print(e)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[[1 4]
  [2 5]
  [3 6]]]


In [77]:
#numpy splitting array - reverse operation of joining
# use array_split()

a = np.array([1,2,3,4,5,6])
b = np.array_split(a,3)
print(b)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [78]:
# what if the elements are less
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,4) # dont use split() , try to use array_split() - it adjust elemnt
print(b)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [80]:
# split into array
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,3)
print(b[0])
print(b[1])
print(b[2])

[1 2]
[3 4]
[5 6]


In [84]:
# split 2d array
a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
b = np.array_split(a,3)
print(b)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [85]:
# split 2d array
a = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
b = np.array_split(a,4)
print(b)


[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10]]), array([[11, 12]])]


In [86]:
# split the 2d array into 3 2d as per row
a = np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9],[9,10,11],[11,12,13]])
b = np.array_split(a,3, axis = 1)
print(b)


[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([[ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13]])]


In [88]:
#use hsplit or hstack method to split the 2d array into 2d array along with rows
a = np.array([[1,2,3],[3,4,5],[5,6,7],[7,8,9],[9,10,11],[11,12,13]])
b = np.hsplit(a,3)
print(b)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([[ 3],
       [ 5],
       [ 7],
       [ 9],
       [11],
       [13]])]


In [90]:
# numpy searching array
# where()

a = np.array([1,2,3,4,5,4,6,7,4])
x = np.where(a ==4)
print(x)

(array([3, 5, 8]),)


In [91]:
#find index where value are even

a = np.array([1,2,3,4,5,6,7,8])
x = np.where(a%2 ==0)
print(x)

(array([1, 3, 5, 7]),)


In [92]:
#find the index where value are odd

a = np.array([1,2,3,4,5,4,6,7,4])
x = np.where(a%2 ==1)
print(x)

(array([0, 2, 4, 7]),)


In [104]:
# searchsorted() method by default from left to right
x = np.array([5,6,7,8,9])
b = np.searchsorted(x,7)
print(b)

2


In [107]:
# search from right to left
x1 = np.array([5,6,7,8])
b1 = np.searchsorted(x1,8,side='right')
print(b1)

4


In [108]:
#searching multiple values 

x = np.array([1,3,5,7])
b = np.searchsorted(x,[2,4,6])
print(b)

[1 2 3]


In [110]:
# numpy sorting arrays
# sort()
a = np.array([3,2,0,1])
print(np.sort(a))
print(a)

[0 1 2 3]
[3 2 0 1]


In [111]:
#we can sort any data type

a = np.array(['apple','banana','orange','kiwi'])
print(np.sort(a))

['apple' 'banana' 'kiwi' 'orange']


In [112]:
# sorting two d array
a = np.array([[3,2,0],[1,3,2]])
print(np.sort(a))

[[0 2 3]
 [1 2 3]]


In [113]:
#numpy array filter 
#create an array from the element on index 0 to 2

a = np.array([41,42,43,44])
x = [True,False,True,False]
b = a[x]
print(b)

[41 43]


In [114]:
# creating the filter array
a = np.array([41,42,43,44])
#create an empty list
b = []
for i in a:
    if i > 42:
        b.append(True)
    else:
        b.append(False)
c = a[b]
print(b)
print(c)

[False, False, True, True]
[43 44]


In [115]:
#numpy random numbers
#this is random number generated through a algorith called pseudo random
from numpy import random

a = random.randint(100)
print(a)

96


In [118]:
# for random float
a = random.rand()
print(a)

0.2709205373617005


In [119]:
# generate random arrays() - 1D

from numpy import random

a1 = random.randint(100,size=(5))
print(a1)


[26 58 74 53 95]


In [120]:
# generate random arrays() - 2D

from numpy import random

a2 = random.randint(100,size=(3,5))
print(a2)

[[20 96  0 69 40]
 [68 38 34 52 85]
 [76 30 75 29  1]]


In [121]:
# for floating 1D
a = random.rand(5)
print(a)

[0.22748315 0.47574042 0.93519514 0.22917048 0.0028597 ]


In [122]:
#for genrating 2d array
a1 = random.rand(3,5)
print(a1)


[[0.76336746 0.56299923 0.79662144 0.40502711 0.3415841 ]
 [0.78645742 0.14076023 0.3506033  0.6805513  0.39468395]
 [0.68552311 0.31142168 0.56562941 0.36098188 0.43983948]]


In [123]:
# generate random number from an array
# choice()
from numpy import random
a = random.choice([3,5,6,7])
print(a)

3


In [126]:
# generate a 2D from the random array
a = random.choice([3,4,5,6,9],size=(3,4))
print(a)

[[3 5 6 9]
 [6 3 5 5]
 [4 4 4 9]]
